### ISSUE TITLE
Decky 2.10.4 has broken certain QAM Menu elements

### ISSUE THREAD

**Issue by recursive-albedo** [Kalyvara/CSS-Loader-releases#7]
See for example: borders fail to extend properly around QAM menu headers
![image](https://github.com/Kalyvara/CSS-Loader-releases/assets/56356653/9dce4105-1ddc-4247-adc3-63b7603db876)

In addition, it seems the side bar colour toggles no longer affect the CSS either, switching their colour outputs (for example) does not have any changes take place.

**Comment by Kalyvara** [comment]
I've just updated to Decky 2.10.4 and I can't seem to reproduce the header title bug. Do you have any other themes installed that might conflict with CapyMenu? What Steam update channel are you on?

Also FYI it isn't intended for the border to appear at all (as opposed to Material You for example), it's supposed to be completely hidden... normally

As for the side bar color selector, this is also working fine on my end. Since the introduction of the Soundtracks tab, the tabs take up all the vertical space available, making their column container hidden underneath. Make sure to either:

- change the background color of the tabs themselves, not the column container's
- or, set the tabs' background opacity to 0, and change the background color of the column

**Comment by recursive-albedo** [comment]
I'm on the stable update channel, but it could very well be another plugin messing with it so I will give those a try and see where I can get to. Thanks for the tips.
